stages:
  - deploy

deploy_staging:
  stage: deploy
  when: manual
  tags:
    - storyboard-uat
  only:
    - staging
  script:
    - /usr/bin/npm install
    # Todo: Use --prod while generating the build
    - ng build
    - cp -r dist/project-test /opt/soroco/www/storyboard/
    - rm -rf /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/static /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/project-test /opt/soroco/www/storyboard/static


deploy_production:
  stage: deploy
  when: manual
  tags:
    - storyboard
  only:
    - master
  script:
    - /usr/bin/npm install
    # Todo: Use --prod while generating the build
    - ng build
    - cp -r dist/project-test /opt/soroco/www/storyboard/
    - rm -rf /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/static /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/project-test /opt/soroco/www/storyboard/static
