stages:
  - inspection
  - deploy

code-format:
  image: trion/ng-cli-karma
  stage: inspection
  tags:
    - docker
  script:
    - npm install
    - npm run format:check
  allow_failure: true

lint:
  image: trion/ng-cli-karma
  stage: inspection
  tags:
    - docker
  script:
    - npm install
    - npm run lint
  allow_failure: true

deploy_staging:
  stage: deploy
  when: manual
  tags:
    - storyboard-uat
  only:
    - staging
  script:
    - /usr/bin/npm install
    # Todo: Use --prod while generating the build
    - ng build
    - cp -r dist/storyboard-frontend /opt/soroco/www/storyboard/
    - rm -rf /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/static /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/storyboard-frontend /opt/soroco/www/storyboard/static

deploy_production:
  stage: deploy
  when: manual
  tags:
    - storyboard
  only:
    - master
  script:
    - /usr/bin/npm install
    # Todo: Use --prod while generating the build
    - ng build
    - cp -r dist/storyboard-frontend /opt/soroco/www/storyboard/
    - rm -rf /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/static /opt/soroco/www/storyboard/static-bkp
    - mv /opt/soroco/www/storyboard/storyboard-frontend /opt/soroco/www/storyboard/static
