resources:
  containers:
    - container: ng_cli_karma
      image: trion/ng-cli-karma
      options: --net host

jobs:
  - job: format_lint_test
    pool:
      name: Storyboard
      demands:
        - agent.name -equals Storyboard-UAT
    container: ng_cli_karma
    steps:
      - script: npm install
        displayName: install npm packages
      - script: npm run format:check
        condition: succeededOrFailed()
        displayName: format check
      - script: npm run lint
        condition: succeededOrFailed()
        continueOnError: true
        displayName: tslint check
      - script: npm run test:CI
        condition: succeededOrFailed()
        displayName: run unit tests
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          { testResultsFormat: "JUnit", testResultsFiles: "**/TESTS-*.xml" }
      - task: PublishCodeCoverageResults@1
        condition: succeededOrFailed()
        inputs:
          {
            codeCoverageTool: Cobertura,
            summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*cobertura-coverage.xml",
          }

  - job: build
    pool:
      name: Storyboard
      demands:
        - agent.name -equals Storyboard-UAT
    condition: and(succeededOrFailed(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    steps:
      - bash: |
          /usr/bin/npm install
          ng build
        displayName: "Angular build"
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "dist/"
          artifactName: dist
          displayName: Save generated content
