jobs:
  - job: build
    pool:
      name: Storyboard
      demands:
        - agent.name -equals Storyboard-UAT
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    steps:
      - bash: |
          /usr/bin/npm install
          ng build
        displayName: "Angular build"
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "dist/"
          artifactName: dist
          displayName: Save generated content
