jobs:
  - job: build
    pool:
      name: Storyboard
      demands:
      - agent.name -equals Storyboard-UAT
    steps:
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'npm build'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ng build'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: dist'
        inputs:
          PathtoPublish: dist
          ArtifactName: dist
