jobs:
  - job: build
    pool:
      name: Storyboard
      demands:
      - agent.name -equals Storyboard-UAT
    steps:
      - bash: |
          /usr/bin/npm install
          ng build
        displayName: 'Angular build'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'dist/'
          artifactName: dist
          displayName: Save generated content
